name: Auto Attendance

on:
  schedule:
    - cron: '0 4,16 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Cache Data
      id: cache-tjupt-attendance-data
      uses: actions/cache@v2
      with:
        path: data
        key: ${{ runner.os }}-data
      continue-on-error: true
    - name: Auto Attendance
      run: |
        python main.py -u "${{ secrets.USERNAME }}" -p "${{ secrets.PASSWORD }}"
      continue-on-error: true